version: '3'

services:
  alt-sch-go:
    build: . #search for Dockerfile
    container_name: school_mgt_system
    volumes:
      - .:/go/src/go-docker
    ports:
      - "8080:8080"
    networks:
      - school_system

  mysql:
    image: mysql:latest
    #    command:
    #      - '--character-set-server=utf8mb4'
    restart: unless-stopped
    tty: true
    container_name: school_mgt_system
    ports:
      - "3307:3306"
    volumes:
      - .:/var/lib
      - ./mysql:/var/lib/mysql
      - ./mysql-files:/var/lib/mysql-files
    environment:
      MYSQL_DATABASE: school_ms
      MYSQL_PASSWORD: mysqlsecret
      MYSQL_ROOT_PASSWORD: mysqlsecret
    networks:
      - school_system

networks:
  school_system:
    external: true